### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by Agwebberley** [adiantek/mc-spx#16]
Could support for 1.19.2 be added?

**Comment by SUB0PT1MAL** [comment]
You can do it yourself, open the 1.19.2.json file and modify the fields that 1.19-aarch64.json has modified from the 1.19.json

I did it and it works.

**Comment by Eporfhin** [comment]
> You can do it yourself, open the 1.19.2.json file and modify the fields that 1.19-aarch64.json has modified from the 1.19.json
> 
> I did it and it works.

Then how did you create the jar file? I have tried for a long time without success:(

**Comment by SUB0PT1MAL** [comment]
I created a merge request to the repo maintainers, if they accept it you will have the .json file for 1.19.2 available.

**Comment by adiantek** [comment]
@SUB0PT1MAL I merged it, now 1.19.2 is available.
