### ISSUE TITLE
optifine

### ISSUE THREAD

**Issue by FoxbitDreamtail** [adiantek/mc-spx#2]
how do I install optifine to improve performance on my low-end arm pc (Rpi4 running WoR Heavily debloated)?

**Comment by adiantek** [comment]
You can't without modify Optifine by-self: https://github.com/sp614x/optifine/issues/5739

**Comment by FoxbitDreamtail** [comment]
then what about other enhancements like Sodium?

**Comment by adiantek** [comment]
Never heard about Sodium, but it's an interesting project. I think Sodium should works.

**Comment by FoxbitDreamtail** [comment]
just one question... how do I install fabric and subsequently sodium?

**Comment by FoxbitDreamtail** [comment]
nevermind.... i tried and failed at running Sodium on my rpi4.... btw, I am not running RpiOS, this is the last insider build of Win10 I'm running on my pi.

**Comment by FoxbitDreamtail** [comment]
How do I manually edit OptiFine to run on the arm64 build of Minecraft

**Comment by adiantek** [comment]
For Surface Pro X:
https://github.com/sp614x/optifine/issues/5739#issuecomment-875187797 is fixed, so:
1. Download `1.17.1-aarch64` from this repository and install it to .minecraft -> versions.
2. Run this version using https://github.com/microsoft/openjdk-aarch64/releases
3. Download the latest optifine.net.
4. Install it (`"C:\Program Files (Arm)\Java\jdk-16-ea+19-windows-aarch64\bin\java.exe" -jar OptiFine_1.17.1_HD_U_G9.jar` in my case).
5. Edit in `1.17.1-OptiFine_HD_U_G9.json`: change from `"inheritsFrom": "1.17.1",` to `"inheritsFrom": "1.17.1-aarch64",`.
6. Run `1.17.1-OptiFine_HD_U_G9` using also Java for arm64.
Tested and it works on Surface Pro X, so I think it should work fine for your RPI with Win10 arm64.
