### ISSUE TITLE
Copying JSON folder to %appdata%\.minecraft\version fails

### ISSUE THREAD

**Issue by mijk84** [adiantek/mc-spx#9]
It just creates 1.17.1 folder with its own JSON file in it. Renaming the downloaded JSON and replacing the one in 1.17.1 folder only causes the game to crash.

**Comment by adiantek** [comment]
You must create a new directory like in a github repository named `1.17.1-aarch64` and inside this directory `1.17.1-aarch64.json`. Just download the ZIP of this repository and extract it to versions.
